# Generated by Django 4.2 on 2023-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='pictures/products', verbose_name='Картинка')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламный баннер',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DealerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование юридического лица')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('city', models.CharField(max_length=100, verbose_name='Город осуществления деятельности*')),
                ('shops', models.IntegerField(verbose_name='Кол-во магазинов')),
                ('sales_type', models.CharField(choices=[('Розница', 'Розница'), ('Оптовые', 'Оптовые')], max_length=100, verbose_name='Тип продаж')),
                ('text', models.TextField(verbose_name='Доп. инфо')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заявка дилера',
                'verbose_name_plural': 'Заявки дилеров',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='pictures/products', verbose_name='Картинка')),
                ('info', models.TextField(verbose_name='Описание')),
                ('background_color', models.CharField(blank=True, choices=[('#000000', 'Black'), ('grey', 'Grey'), ('#ffffff', 'White')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/products', verbose_name='Картинка')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='pictures/products', verbose_name='Картинка #2')),
                ('os_type', models.CharField(blank=True, choices=[('android', 'android'), ('webos', 'webos')], max_length=100, verbose_name='Тип ОС')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый')),
                ('display', models.CharField(blank=True, max_length=255, verbose_name='Экран')),
                ('resolution', models.CharField(blank=True, max_length=255, verbose_name='Разрешение')),
                ('brightness', models.CharField(blank=True, max_length=255, verbose_name='Яркость')),
                ('contrast', models.CharField(blank=True, max_length=255, verbose_name='Контраст')),
                ('voice', models.CharField(blank=True, max_length=255, verbose_name='Звук')),
                ('ac', models.CharField(blank=True, max_length=255, verbose_name='Блок питания')),
                ('system', models.CharField(blank=True, max_length=255, verbose_name='Система')),
                ('wifi', models.CharField(blank=True, max_length=255, verbose_name='Wi-Fi/Bluetooth')),
                ('ram', models.CharField(blank=True, max_length=255, verbose_name='RAM/DDR')),
                ('voice_control', models.BooleanField(default=False, verbose_name='Голосовое управление')),
                ('tech', models.CharField(blank=True, max_length=255, verbose_name='Технологии')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на товар')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=255, verbose_name='Серия')),
                ('talon', models.CharField(max_length=255, verbose_name='Талон')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('dealer', models.CharField(max_length=255, verbose_name='Дилер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Активированная гарантия',
                'verbose_name_plural': 'Активированные гарантии',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=255, verbose_name='Серия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'База Серий',
                'verbose_name_plural': 'База Серий',
                'ordering': ['-created'],
            },
        ),
    ]
