# Generated by Django 4.2 on 2023-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='descripton',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imag1',
            field=models.ImageField(default='', upload_to='products', verbose_name='picture-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='products', verbose_name='picture-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(default='', max_length=255, verbose_name='OS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='os_info',
            field=models.TextField(default='', verbose_name='OS info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Price'),
        ),
    ]
