# Generated by Django 4.2 on 2023-05-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_image_product_descripton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imag1',
            new_name='image1',
        ),
    ]
