# Generated by Django 4.2 on 2023-05-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_characteristics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristics',
            new_name='character',
        ),
    ]
