# Generated by Django 4.2 on 2023-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image',
            field=models.ImageField(upload_to='pictures/products', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='pictures/products', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='pictures/products', verbose_name='picture-1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/products', verbose_name='picture-2'),
        ),
    ]
