# Generated by Django 4.2 on 2023-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_warrantydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование юридического лица')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('city', models.CharField(max_length=100, verbose_name='Город осуществления деятельности*')),
                ('shops', models.IntegerField(verbose_name='Кол-во магазинов')),
                ('sales_type', models.CharField(choices=[('Розница', 'Розница'), ('Оптовые', 'Оптовые')], max_length=100, verbose_name='Тип продаж')),
                ('text', models.TextField(verbose_name='Доп. инфо')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'DealerRequest',
                'verbose_name_plural': 'DealerRequests',
            },
        ),
        migrations.AlterModelOptions(
            name='adverts',
            options={'ordering': ['-created'], 'verbose_name': 'Рекламный баннер', 'verbose_name_plural': 'Рекламный баннер'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['-created'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['-created'], 'verbose_name': 'Активированная гарантия', 'verbose_name_plural': 'Активированные гарантии'},
        ),
        migrations.AlterModelOptions(
            name='warrantydata',
            options={'ordering': ['-created'], 'verbose_name': 'База Серий', 'verbose_name_plural': 'База Серий'},
        ),
        migrations.AlterField(
            model_name='adverts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image',
            field=models.ImageField(upload_to='pictures/products', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#ffffff', 'White'), ('#000000', 'Black'), ('grey', 'Grey')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='pictures/products', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='info',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='character',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripton',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='pictures/products', verbose_name='Картинка-1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/products', verbose_name='Картинка-2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os_info',
            field=models.TextField(blank=True, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='dealer',
            field=models.CharField(max_length=255, verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='series',
            field=models.CharField(max_length=255, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='talon',
            field=models.CharField(max_length=255, verbose_name='Талон'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='warrantydata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='warrantydata',
            name='series',
            field=models.CharField(max_length=255, unique=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='warrantydata',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
