# Generated by Django 4.2 on 2023-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_dealerrequest_alter_adverts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#ffffff', 'White'), ('grey', 'Grey'), ('#000000', 'Black')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='warrantydata',
            name='series',
            field=models.CharField(max_length=255, verbose_name='Серия'),
        ),
    ]
