# Generated by Django 4.2 on 2023-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_partners_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('grey', 'Grey'), ('#000000', 'Black'), ('#ffffff', 'White')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
    ]
