# Generated by Django 4.2 on 2023-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_dealerrequest_options_remove_product_character_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='is_new',
        ),
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('#ffffff', 'White'), ('grey', 'Grey')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os_type',
            field=models.CharField(blank=True, choices=[('android', 'android'), ('webos', 'webos')], max_length=100, verbose_name='Тип ОС'),
        ),
    ]
