# Generated by Django 4.2 on 2023-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_new_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#ffffff', 'White'), ('#000000', 'Black'), ('grey', 'Grey')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
    ]
