# Generated by Django 4.2 on 2023-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_product_url_alter_partners_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('#ffffff', 'White'), ('grey', 'Grey')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
    ]
