# Generated by Django 4.2 on 2023-07-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_partners_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('grey', 'Grey'), ('#ffffff', 'White')], default='#ffffff', max_length=255, null=True, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os_type',
            field=models.CharField(blank=True, choices=[('android', 'android'), ('webos', 'webos')], max_length=100, verbose_name='Тип ОС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/products', verbose_name='Картинка'),
        ),
    ]
